### PR TITLE
Fix inconsistent ServiceCard width on mobile view

### PR DESCRIPTION
**Pull request by parksaerom**
Device: iPhone 13

Previously:
- Card widths on mobile view were inconsistent, causing a misaligned and uneven layout.

reactjs18-3d-portfolio

Now:
- Card widths are consistent across mobile view, providing a uniform and cleaner layout.

reactjs18-3d-portfolio_2

### CODE REVIEW

**Comment by ladunjexa** [comment]
Hi,

The changes you made are affecting the display on other devices. To avoid this, please target the dimensions of the iPhone 13 and set the width accordingly.

You can refer to the following links for guidance: [Responsive Design](https://tailwindcss.com/docs/responsive-design) and using [Custom Breakpoints](https://tailwindcss.com/docs/responsive-design#custom-breakpoints).

Thanks for your contribution :)

**Comment by parksaerom** [comment]
@ladunjexa 
Hi,

Currently, the width is set to 250px for all non-mobile devices, but I believe that setting it to 250px for mobile as well would be more appropriate. Could you please clarify which devices are targeted by the w-full setting?

Thanks for your feedback!

**Comment by ladunjexa** [comment]
@parksaerom when using fixed pixels sizes, dimensions remain constant across all devices; for example, a div set to 250px wide will always be 250px, regardless of screen size or resolution. This can lead to visibility issues on smaller or larger devices, unlike using `w-full` (which translates to `width: 100%` in tailwind).

It seems that the initial size of the div doesn't handle all cases (for example, on your device), but relying on a single option wouldn't be the right solution either.

If you'd like to contribute, please test on different devices, ideally using tailwind breakpoints (I just checked in the tailwind config and there isn't custom breakpoints), and attach screenshots for reference.

**Comment by parksaerom** [comment]
@ladunjexa

Previously (xs:w-[250px] w-full): 
image

Now (max-w-[250px] w-full xs:w-[250px]):
image

Updated card width to use max-w-[250px] and w-full for better responsiveness on smaller screens. Ensures cards are flexible on small devices while maintaining consistent width on larger screens.

Feel free to let me know if any further changes are needed!

**Pull request merged**
